# Generated by Django 4.2 on 2023-04-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="default/default.jpg", upload_to="products/"
            ),
        ),
    ]
