# Generated by Django 4.2 on 2023-04-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="default/default.jpg", upload_to="static/media/products/"
            ),
        ),
    ]
